export const translations: {[id: string]: string} = {
  language: 'language',
  languagePrefix: 'en',
  feature: 'Feature',
  featureDescription: 'Brief description of the feature',
  scenario: 'Scenario',
  scenarioDescription: 'Brief description of the scenario',
  given: 'Given',
  when: 'When',
  then: 'Then',
  context: 'context',
  condition: 'condition',
  result: 'result',
  featureDocumentation: 'Create a feature',
  scenarioDocumentation: 'Create a scenario',
  head: 'head',
  value: 'value',
  table: 'table',
};
